In [ ]:
import numpy as np
crop_yield=np.array([
    [12.5,2.4,6.5,5.5,8.7],
    [12.5,2.4,6.5,5.5,8.7],
    [2.3,5.8,8.9,9.0,9.0],
    [2.3,5.8,8.9,9.0,9.0] ,
    [7.3,5.8,8.9,9.0,9.0]

])
print(crop_yield)
print(crop_yield.shape)
print(crop_yield.dtype)
print(crop_yield.size)
print(crop_yield.ndim)

[[12.5  2.4  6.5  5.5  8.7]
 [12.5  2.4  6.5  5.5  8.7]
 [ 2.3  5.8  8.9  9.   9. ]
 [ 2.3  5.8  8.9  9.   9. ]
 [ 7.3  5.8  8.9  9.   9. ]]
(5, 5)
float64
25
2


In [ ]:
total_yield=np.sum(crop_yield)
avg_farm=np.mean(crop_yield,axis=1)
avg_yield_per_season=np.mean(crop_yield,axis=0)
print(total_yield)
print(avg_farm)
print(avg_yield_per_season)
max_yield=np.max(crop_yield)
min_yield=np.min(crop_yield)

181.20000000000002
[7.12 7.12 7.   7.   8.  ]
[7.38 4.44 7.94 7.6  8.88]


In [ ]:
best_farm=np.argmax(avg_farm)
print(best_farm+1)

5


In [ ]:
exceptional=crop_yield>9
print(exceptional)
print(crop_yield[exceptional])

[[ True False False False False]
 [ True False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[12.5 12.5]


In [ ]:
categories=np.where